name: Turborepo Prysk Tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  turborepo_integration:
    name: Turborepo Integration Tests
    # if: needs.determine_jobs.outputs.turborepo_integration == 'true'
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu
            runner: ubuntu-latest
          - name: macos
            runner: macos-latest
          - name: windows
            runner: windows-latest
    steps:
      # On Windows, set autocrlf to input so that when the repo is cloned down
      # the fixtures retain their line endings and don't get updated to CRLF.
      # We want this because this repo also contains the fixtures for our test cases
      # and these fixtures have files that need stable file hashes. If we let git update
      # the line endings on checkout, the file hashes will change.
      # https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf
      - name: set crlf
        if: matrix.os.name == 'windows'
        shell: bash
        run: git config --global core.autocrlf input

      # We use rsync for some integration tests to copy fixture files when they contain symlinks
      # because `cp` on Windows doesn't seem to preserve symlinks.
      - name: Install rsync
        if: matrix.os.name == 'windows'
        run: choco install rsync -y

      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-turborepo-environment
        with:
          windows: ${{ matrix.os.name == 'windows' }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Cache Prysk
        id: cache-prysk
        uses: actions/cache@v3
        with:
          path: cli/.cram_env
          key: prysk-venv-${{ matrix.os.name }}

      - name: Integration Tests
        run: turbo run test --filter=turborepo-tests-integration --color --env-mode=strict --token=${{ secrets.TURBO_TOKEN }} --team=${{ vars.TURBO_TEAM }}
        shell: bash
        env:
          EXPERIMENTAL_RUST_CODEPATH: true
